"""Minimal Phase 5 skill installer — writes scaffold SKILL.md files to target dirs.

Phase 7 will replace the placeholder bodies with the full skill content
described in ``docs/`` and add per-platform path discovery (Claude
project root, Codex .agents, Antigravity HOME). For Phase 5 we only need
the shape the MCP ``agy_install_skill`` tool returns: a structured list
of installed files plus any warnings.

The scaffold is intentionally short so a Phase 7 rewrite cannot leave a
half-installed skill on disk — every file is overwritten with the same
content idempotently.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Literal

from agy_mcp.safety import SafetyPolicy

SkillTarget = Literal["claude", "codex", "antigravity", "all"]
SkillScope = Literal["user", "project"]

_PLACEHOLDER_BODY = """---
name: collaborating-with-antigravity
description: Phase 5 scaffold. Phase 7 will replace this with the full collaboration playbook.
---

# Collaborating with Antigravity (scaffold)

This is a placeholder generated by ``agy-install-skill``. The full
skill body lands in Phase 7; until then, use ``agy-bridge --help`` for
the CLI reference and ``python -m agy_mcp`` for the MCP server.
"""


@dataclass(slots=True)
class InstallEntry:
    target: str
    scope: str
    path: str
    overwrote: bool


@dataclass(slots=True)
class InstallResult:
    installed: list[InstallEntry] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    error: str | None = None

    @property
    def success(self) -> bool:
        return self.error is None

    def to_dict(self) -> dict:
        return {
            "success": self.success,
            "error": self.error,
            "warnings": list(self.warnings),
            "installed": [
                {
                    "target": e.target,
                    "scope": e.scope,
                    "path": e.path,
                    "overwrote": e.overwrote,
                }
                for e in self.installed
            ],
        }


def install_skills(
    *,
    targets: Iterable[SkillTarget] = ("all",),
    scope: SkillScope = "user",
    project_root: Path | None = None,
    safety: SafetyPolicy | None = None,
) -> InstallResult:
    """Write the scaffold skill to each requested target.

    ``project_root`` is required when ``scope="project"``. ``safety`` is
    used only to redact paths in the returned envelope so a future MCP
    transcript or log capture cannot leak the operator's home directory.
    """

    sft = safety or SafetyPolicy()
    chosen = _expand_targets(targets)
    if scope == "project" and project_root is None:
        return InstallResult(error=sft.redact("scope='project' requires project_root"))

    result = InstallResult()
    for target in chosen:
        try:
            target_dir = _resolve_target_dir(target, scope, project_root)
        except ValueError as exc:
            result.warnings.append(sft.redact(str(exc)))
            continue
        skill_dir = target_dir / "collaborating-with-antigravity"
        skill_file = skill_dir / "SKILL.md"
        try:
            skill_dir.mkdir(parents=True, exist_ok=True)
            overwrote = skill_file.exists()
            skill_file.write_text(_PLACEHOLDER_BODY, encoding="utf-8")
        except OSError as exc:
            result.warnings.append(sft.redact(f"install to {skill_file} failed: {exc}"))
            continue
        result.installed.append(
            InstallEntry(
                target=target,
                scope=scope,
                path=sft.redact(str(skill_file)),
                overwrote=overwrote,
            )
        )

    if not result.installed and not result.warnings:
        result.error = sft.redact("no targets installed")
    return result


# ---------------------------------------------------------------------------
# Path discovery
# ---------------------------------------------------------------------------


_USER_SKILL_DIRS: dict[str, Path] = {
    "claude": Path.home() / ".claude" / "skills",
    "codex": Path.home() / ".agents" / "skills",
    "antigravity": Path.home() / ".gemini" / "antigravity-cli" / "skills",
}

_PROJECT_SKILL_DIRS: dict[str, Path] = {
    "claude": Path(".claude") / "skills",
    "codex": Path(".agents") / "skills",
    "antigravity": Path(".antigravity") / "skills",
}


def _expand_targets(targets: Iterable[SkillTarget]) -> list[str]:
    out: list[str] = []
    for t in targets:
        if t == "all":
            out.extend(["claude", "codex", "antigravity"])
        elif t in _USER_SKILL_DIRS:
            out.append(t)
        else:
            raise ValueError(f"unknown skill target: {t!r}")
    seen: set[str] = set()
    deduped: list[str] = []
    for t in out:
        if t not in seen:
            deduped.append(t)
            seen.add(t)
    return deduped


def _resolve_target_dir(target: str, scope: str, project_root: Path | None) -> Path:
    if scope == "user":
        if target not in _USER_SKILL_DIRS:
            raise ValueError(f"unknown user-scope target: {target!r}")
        return _USER_SKILL_DIRS[target]
    if project_root is None:
        raise ValueError("project_root required for project scope")
    if target not in _PROJECT_SKILL_DIRS:
        raise ValueError(f"unknown project-scope target: {target!r}")
    return project_root / _PROJECT_SKILL_DIRS[target]


# ---------------------------------------------------------------------------
# CLI entry point (kept so ``agy-install-skill`` console script still works)
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    """Minimal CLI shim. Phase 7 will swap in argparse + richer flags."""

    args = list(argv if argv is not None else sys.argv[1:])
    scope: SkillScope = "user"
    targets: list[SkillTarget] = ["all"]
    project_root: Path | None = None
    while args:
        arg = args.pop(0)
        if arg == "--scope" and args:
            scope_val = args.pop(0)
            if scope_val not in ("user", "project"):
                print(f"unknown scope: {scope_val!r}", file=sys.stderr)
                return 2
            scope = scope_val  # type: ignore[assignment]
        elif arg == "--target" and args:
            targets = [t.strip() for t in args.pop(0).split(",") if t.strip()]  # type: ignore[list-item]
        elif arg == "--project-root" and args:
            project_root = Path(args.pop(0))
        else:
            print(f"unknown arg: {arg!r}", file=sys.stderr)
            return 2
    res = install_skills(targets=targets, scope=scope, project_root=project_root)
    for entry in res.installed:
        print(f"installed: {entry.target} {entry.scope} {entry.path}")
    for w in res.warnings:
        print(f"warning: {w}", file=sys.stderr)
    if res.error:
        print(f"error: {res.error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))


__all__ = [
    "InstallEntry",
    "InstallResult",
    "SkillScope",
    "SkillTarget",
    "install_skills",
    "main",
]
