"""Minimal Phase 5 skill installer — writes scaffold SKILL.md files to target dirs.

Phase 7 will replace the placeholder bodies with the full skill content
described in ``docs/`` and audit the per-platform path discovery once
the Antigravity CLI actually documents a skills load path. For Phase 5
we only need the shape the MCP ``agy_install_skill`` tool returns: a
structured list of installed files plus any warnings.

Hardening landed in Phase 5 R1:

* The ``antigravity`` user-scope target was REMOVED because the planned
  write location (`~/.gemini/antigravity-cli/skills`) violates the
  user's standing rule "不修改 ~/.gemini/ 下任何文件" and the agy CLI
  has no documented skill load path. Phase 7 will pick a wrapper-owned
  directory (e.g. ``~/.agy/skills``) once the Antigravity team
  publishes one.
* ``project_root`` is validated: it must be an existing directory whose
  resolved path is itself, not a symlink, and the resulting
  ``<root>/<scope-dir>/<skill>/SKILL.md`` path must remain inside the
  resolved root.
* Writes go through :func:`safe_write_text` so a pre-planted symlink at
  the destination cannot redirect the scaffold body.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Literal

from agy_mcp.safety import SafetyPolicy
from agy_mcp.utils import safe_write_text

SkillTarget = Literal["claude", "codex", "antigravity", "all"]
SkillScope = Literal["user", "project"]

_PLACEHOLDER_BODY = """---
name: collaborating-with-antigravity
description: Phase 5 scaffold. Phase 7 will replace this with the full collaboration playbook.
---

# Collaborating with Antigravity (scaffold)

This is a placeholder generated by ``agy-install-skill``. The full
skill body lands in Phase 7; until then, use ``agy-bridge --help`` for
the CLI reference and ``python -m agy_mcp`` for the MCP server.
"""


@dataclass(slots=True)
class InstallEntry:
    target: str
    scope: str
    path: str
    overwrote: bool


@dataclass(slots=True)
class InstallResult:
    installed: list[InstallEntry] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    error: str | None = None

    @property
    def success(self) -> bool:
        return self.error is None

    def to_dict(self) -> dict:
        return {
            "success": self.success,
            "error": self.error,
            "warnings": list(self.warnings),
            "installed": [
                {
                    "target": e.target,
                    "scope": e.scope,
                    "path": e.path,
                    "overwrote": e.overwrote,
                }
                for e in self.installed
            ],
        }


def install_skills(
    *,
    targets: Iterable[SkillTarget] = ("all",),
    scope: SkillScope = "user",
    project_root: Path | None = None,
    safety: SafetyPolicy | None = None,
) -> InstallResult:
    """Write the scaffold skill to each requested target.

    ``project_root`` is required when ``scope="project"``. ``safety`` is
    used only to redact paths in the returned envelope so a future MCP
    transcript or log capture cannot leak the operator's home directory.
    """

    sft = safety or SafetyPolicy()
    if scope not in ("user", "project"):
        return InstallResult(error=sft.redact(f"scope must be 'user' or 'project', got {scope!r}"))
    try:
        chosen = _expand_targets(targets)
    except ValueError as exc:
        return InstallResult(error=sft.redact(str(exc)))

    validated_root: Path | None = None
    if scope == "project":
        if project_root is None:
            return InstallResult(error=sft.redact("scope='project' requires project_root"))
        try:
            validated_root = _validate_project_root(project_root)
        except ValueError as exc:
            return InstallResult(error=sft.redact(str(exc)))

    result = InstallResult()
    for target in chosen:
        try:
            target_dir = _resolve_target_dir(target, scope, validated_root)
        except ValueError as exc:
            result.warnings.append(sft.redact(str(exc)))
            continue
        skill_dir = target_dir / "collaborating-with-antigravity"
        skill_file = skill_dir / "SKILL.md"
        if scope == "project":
            # Containment check: the resolved skill_file must remain
            # under validated_root. Defense in depth against a target
            # name that snuck a ``..`` past _resolve_target_dir.
            assert validated_root is not None
            try:
                resolved_target = (target_dir).resolve()
                resolved_target.relative_to(validated_root)
            except (OSError, ValueError):
                result.warnings.append(
                    sft.redact(f"skill dir {skill_dir} escapes project_root"),
                )
                continue
            # Refuse to write through a pre-existing symlinked skill_dir.
            if skill_dir.exists() and skill_dir.is_symlink():
                result.warnings.append(
                    sft.redact(f"refusing to write through symlinked skill_dir {skill_dir}"),
                )
                continue
        try:
            overwrote = skill_file.exists()
            safe_write_text(
                skill_file,
                _PLACEHOLDER_BODY,
                mode=0o644,
                verify_under=validated_root if scope == "project" else None,
            )
        except OSError as exc:
            result.warnings.append(sft.redact(f"install to {skill_file} failed: {exc}"))
            continue
        result.installed.append(
            InstallEntry(
                target=target,
                scope=scope,
                path=sft.redact(str(skill_file)),
                overwrote=overwrote,
            )
        )

    if not result.installed:
        # Surface as failure even when warnings exist, so a caller that
        # asked for ``targets=["antigravity"], scope="user"`` (rejected
        # by the user-scope target list) gets ``success=False`` rather
        # than a silent no-op. Phase 5 R1 sec P1.
        if result.warnings:
            result.error = sft.redact("no targets installed (see warnings)")
        else:
            result.error = sft.redact("no targets installed")
    return result


# ---------------------------------------------------------------------------
# Path discovery
# ---------------------------------------------------------------------------


# Phase 5 R1 sec P1: ``antigravity`` user-scope target removed — writing
# under ~/.gemini/ violates the user's standing rule, and the agy CLI
# does not document a skill load path today. Phase 7 will replace this
# with a wrapper-owned directory.
_USER_SKILL_DIRS: dict[str, Path] = {
    "claude": Path.home() / ".claude" / "skills",
    "codex": Path.home() / ".agents" / "skills",
}

_PROJECT_SKILL_DIRS: dict[str, Path] = {
    "claude": Path(".claude") / "skills",
    "codex": Path(".agents") / "skills",
    "antigravity": Path(".antigravity") / "skills",
}


def _expand_targets(targets: Iterable[SkillTarget]) -> list[str]:
    """Expand ``"all"`` to the supported target list for the current scope."""

    out: list[str] = []
    for t in targets:
        if t == "all":
            # ``all`` only expands to user-scope-safe targets. The
            # antigravity project-scope target is opt-in via an
            # explicit ``targets=["antigravity"]``.
            out.extend(["claude", "codex"])
        elif t in _PROJECT_SKILL_DIRS or t in _USER_SKILL_DIRS:
            out.append(t)
        else:
            raise ValueError(f"unknown skill target: {t!r}")
    seen: set[str] = set()
    deduped: list[str] = []
    for t in out:
        if t not in seen:
            deduped.append(t)
            seen.add(t)
    return deduped


def _validate_project_root(project_root: Path) -> Path:
    """Ensure ``project_root`` is an existing real directory, not a symlink.

    The MCP caller controls this path, so we refuse anything that
    could expand the install blast radius:

    - Path must exist and be a directory.
    - The resolved path must equal the unresolved path (refuses bare
      symlinks at the leaf).
    - We do NOT enforce an allowlist of legal roots — the operator
      gave us this path and bears responsibility for it; we just make
      sure we can't be tricked into writing through a symlink.
    """

    try:
        resolved = project_root.expanduser().resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise ValueError(
            f"project_root does not resolve to a real path: {project_root}: {exc}",
        ) from exc
    if not resolved.is_dir():
        raise ValueError(f"project_root is not a directory: {project_root}")
    if project_root.expanduser().is_symlink():
        raise ValueError(f"project_root is a symlink, refusing: {project_root}")
    return resolved


def _resolve_target_dir(target: str, scope: str, project_root: Path | None) -> Path:
    if scope == "user":
        if target not in _USER_SKILL_DIRS:
            raise ValueError(f"unknown user-scope target: {target!r}")
        return _USER_SKILL_DIRS[target]
    if project_root is None:
        raise ValueError("project_root required for project scope")
    if target not in _PROJECT_SKILL_DIRS:
        raise ValueError(f"unknown project-scope target: {target!r}")
    return project_root / _PROJECT_SKILL_DIRS[target]


# ---------------------------------------------------------------------------
# CLI entry point (kept so ``agy-install-skill`` console script still works)
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    """Minimal CLI shim. Phase 7 will swap in argparse + richer flags."""

    args = list(argv if argv is not None else sys.argv[1:])
    scope: SkillScope = "user"
    targets: list[SkillTarget] = ["all"]
    project_root: Path | None = None
    while args:
        arg = args.pop(0)
        if arg == "--scope" and args:
            scope_val = args.pop(0)
            if scope_val not in ("user", "project"):
                print(f"unknown scope: {scope_val!r}", file=sys.stderr)
                return 2
            scope = scope_val  # type: ignore[assignment]
        elif arg == "--target" and args:
            targets = [t.strip() for t in args.pop(0).split(",") if t.strip()]  # type: ignore[list-item]
        elif arg == "--project-root" and args:
            project_root = Path(args.pop(0))
        else:
            print(f"unknown arg: {arg!r}", file=sys.stderr)
            return 2
    res = install_skills(targets=targets, scope=scope, project_root=project_root)
    for entry in res.installed:
        print(f"installed: {entry.target} {entry.scope} {entry.path}")
    for w in res.warnings:
        print(f"warning: {w}", file=sys.stderr)
    if res.error:
        print(f"error: {res.error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))


__all__ = [
    "InstallEntry",
    "InstallResult",
    "SkillScope",
    "SkillTarget",
    "install_skills",
    "main",
]
